---@meta
-- Provium harness globals — see https://provium.dev (or `learn/docs/4-provium/`).
--
-- Drop this file in your test root so the Lua Language Server stops
-- flagging `test`, `provium`, `wait_until`, and friends as undefined
-- globals. Generated by `provium lsp-setup`.
--
-- Coverage strategy: the common API is typed loosely (string/number
-- args, `any` returns where the real userdata surface is large).
-- The goal is "no undefined-global warnings", not full IDE intellisense.
-- Extend by hand if you want richer completion on a specific userdata.

---@class TestContext
---@field name string
local TestContext = {}

---Raise if `cond` is falsy. Marks the test failed.
---@param cond any
---@param msg string|nil
function TestContext:assert(cond, msg) end

---Raise if `a ~= b`.
---@param a any
---@param b any
---@param msg string|nil
function TestContext:assert_eq(a, b, msg) end

---Raise if `a == b`.
---@param a any
---@param b any
---@param msg string|nil
function TestContext:assert_neq(a, b, msg) end

---Raise if `needle` is not a substring of `haystack`. Both must be strings.
---@param haystack string
---@param needle string
---@param msg string|nil
function TestContext:assert_contains(haystack, needle, msg) end

---Run `fn`; raise if it does NOT raise. Returns the error value `fn` raised.
---@param fn fun()
---@param msg string|nil
---@return any
function TestContext:assert_raises(fn, msg) end

---Mark the test failed and raise with `msg`.
---@param msg string|nil
function TestContext:fail(msg) end

---Skip the test with an optional reason.
---@param reason string|nil
function TestContext:skip(reason) end

---Log a message into the test's output.
---@param msg any
function TestContext:log(msg) end

---Register a test. `body` receives a [TestContext](#TestContext).
---Two call shapes:
---  test("name", function(t) ... end)
---  test("name", {tags={"slow"}, profile="peios"}, function(t) ... end)
---@param name string
---@param meta_or_body table|fun(t: TestContext)
---@param maybe_body? fun(t: TestContext)
function test(name, meta_or_body, maybe_body) end

---Register a test marked TODO; skipped at run time but reported.
---@param reason string|nil
function todo(reason) end

---Call `predicate` repeatedly until it returns truthy, or the timeout
---lapses. Returns the truthy value.
---@param predicate fun(): any
---@param opts? { timeout?: number|string, interval?: number|string, desc?: string }
---@return any
function wait_until(predicate, opts) end

-- ---------------------------------------------------------------------------
-- json
-- ---------------------------------------------------------------------------

json = {}

---Serialise a Lua value to a JSON string.
---@param value any
---@return string
function json.encode(value) end

---Parse a JSON string into a Lua value. Null decodes to nil
---(object keys with null are dropped; array null becomes a hole).
---@param s string
---@return any
function json.decode(s) end

-- ---------------------------------------------------------------------------
-- provium (root Lab)
-- ---------------------------------------------------------------------------

---The root Lab handle. `provium:vm(...)`, `provium:bridge(...)`,
---`provium:lab(...)`, `provium:vm_fixture(...)`, `provium:lab_fixture(...)`,
---`provium:snapshot()`, `provium:restore(...)`, `provium:depends_on_file(...)`
---and the lifecycle methods (boot/shutdown/pause/resume) all live here.
---
---Full surface is too large for stubs — most return values are
---typed as `any`. See `learn/docs/4-provium/content/500-reference/`
---for the real shape of each userdata.
---@class Lab
---@field [string] any
local Lab = {}

---@param name string
---@param profile? string
---@param opts? table
---@return any  -- Vm userdata
function Lab:vm(name, profile, opts) end

---@param name string
---@param opts? table
---@return any  -- Bridge userdata
function Lab:bridge(name, opts) end

---@param name? string
---@return Lab
function Lab:lab(name) end

---@param path string
---@return any  -- Vm userdata restored from the cached fixture
function Lab:vm_fixture(path) end

---@param path string
---@return Lab
function Lab:lab_fixture(path) end

---@param dir? string
---@return any  -- LabSnapshot userdata
function Lab:snapshot(dir) end

---@param dir_or_snapshot any
function Lab:restore(dir_or_snapshot) end

---Declare an external host file as a fixture-cache dependency
---(no-op at runtime — picked up by the static cache-key scanner).
---@param host_path string
function Lab:depends_on_file(host_path) end

function Lab:boot() end
function Lab:shutdown() end
function Lab:pause() end
function Lab:resume() end

---@type Lab
provium = nil

-- ---------------------------------------------------------------------------
-- Internal globals — present at runtime; users rarely reference them
-- directly. Declared here so the LSP doesn't warn when they appear in
-- generated/instrumented code.
-- ---------------------------------------------------------------------------

---@type fun(seconds: number)
_provium_sleep = nil
---@type fun(): number
_provium_now = nil
---@type string
_PROVIUM_SOURCE_PATH = nil
---@type fun(ud: any, kind: string)
_provium_register_resource = nil
---@type fun()
_provium_close_test_scope = nil
---@type fun()
_provium_close_file_scope = nil
---@type fun()
_provium_file_skipped = nil
---@type fun(): table
_provium_get_tests = nil
---@type fun()
_provium_clear_tests = nil
---@type fun(name: string, meta: table?): TestContext
_provium_make_t = nil
---@type table
_provium_file_config = nil
